# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-03-10 00:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Calendar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
            ],
            options={
                'verbose_name_plural': 'Calendars',
                'verbose_name': 'Calendar',
            },
        ),
        migrations.CreateModel(
            name='Lecture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=50)),
                ('lecture', models.TextField(max_length=10000)),
                ('date', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='lectures', to='lectura.Calendar')),
            ],
            options={
                'verbose_name_plural': 'Lectures',
                'verbose_name': 'Lecture',
            },
        ),
    ]
